site_name: Ideamart Documentation
site_url: https://docs.ideamart.io/ideaprov2
site_author: Ideamart
site_description: >-
 Ideamart API and User Documentation to build own app with Ideamart APIs
copyright: Copyright &copy; 2024 Ideamart
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/ideamartlk
theme:
  name: material